name: .NET push on feature branch

on:
  push:
    branches: [feature/*]

jobs:
  build:
    # The virtual machine that will be used on GitHub
    runs-on: ubuntu-latest
    # Run the steps in a Docker container on the virtual machine
    container:
      image: mcr.microsoft.com/dotnet/sdk:8.0@sha256:35792ea4ad1db051981f62b313f1be3b46b1f45cadbaa3c288cd0d3056eefb83
    steps:
      # Checkout Git repository
    - uses: actions/checkout@v3
      # Install the dependencies needed for the project
    - name: Install dependencies
      run: dotnet restore
      # Build the project
    - name: Build
      run: dotnet build
      # Test the project
    - name: Test
      run: dotnet test