name: .NET push on develop branch

on:
  push:
    branches: [develop]

env:
  BUILD_CONFIGURATION: Release

jobs:
  build:
    # The virtual machine that will be used on GitHub
    runs-on: ubuntu-latest
    # Run the steps in a Docker container on the virtual machine
    container:
      image: mcr.microsoft.com/dotnet/sdk:7.0@sha256:d32bd65cf5843f413e81f5d917057c82da99737cb1637e905a1a4bc2e7ec6c8d
    steps:
      # Checkout Git repository
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
      # Install the dependencies needed for the project
    - name: Install dependencies
      run: dotnet restore
      # Build the project
    - name: Build
      run: dotnet build      
      # Test the project
    - name: Test
      run: dotnet test
      # Pack the release build in the /output folder
    - name: Pack
      run: dotnet pack -c ${{ env.BUILD_CONFIGURATION }} -o output
