name: .NET push on main branch

on:
  push:
    tags:
    - 'v**'

env:
  BUILD_CONFIGURATION: Release

jobs:
  build:
    # The virtual machine that will be used on GitHub
    runs-on: ubuntu-latest
    # Run the steps in a Docker container on the virtual machine
    container:
      image: mcr.microsoft.com/dotnet/sdk:8.0@sha256:35792ea4ad1db051981f62b313f1be3b46b1f45cadbaa3c288cd0d3056eefb83
    steps:
      # Checkout Git repository
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
      # Install the dependencies needed for the project
    - name: Install dependencies
      run: dotnet restore
      # Build the project
    - name: Build
      run: dotnet build      
      # Test the project
    - name: Test
      run: dotnet test
      # Pack the release build in the /output folder
    - name: Pack
      run: dotnet pack -c ${{ env.BUILD_CONFIGURATION }} -o output
      # Deliver NuGet package to nuget.org
    - name: Deliver NuGet package to nuget.org
      run: |
        dotnet nuget push ./output/*.nupkg --source "nuget" --api-key ${{ secrets.NUGET_API_KEY }} --skip-duplicate
